"""D-0069 / F-0084: the brief must call a provider this app can authenticate.

The handler required `GROK_API_KEY` and called `api.x.ai`. That key has never
been set on this application, so every brief returned:

    503 GROK_API_KEY not configured

`ANTHROPIC_API_KEY` had been deployed the whole time, and the panel's own
footer has always read "Generated by Claude Haiku". Three things disagreed:
what the UI claimed, what the code called, and what the environment could
authenticate. Nothing compared them.
"""
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTES = ROOT / "api" / "routes.py"
BRIEF_UI = ROOT / "ui" / "src" / "components" / "country" / "AnalystBrief.jsx"


def routes_source():
    return ROUTES.read_text(encoding="utf-8")


class TheBriefCallsAnthropic(unittest.TestCase):
    def test_it_posts_to_the_messages_api(self):
        self.assertIn("https://api.anthropic.com/v1/messages", routes_source())

    def test_it_no_longer_calls_grok(self):
        source = routes_source()
        for stale in ("api.x.ai", "grok-2-latest", "settings.grok_api_key"):
            with self.subTest(stale=stale):
                self.assertNotIn(stale, source)

    def test_it_guards_on_the_key_it_actually_uses(self):
        source = routes_source()
        self.assertIn("settings.anthropic_api_key", source)
        self.assertNotIn("GROK_API_KEY not configured", source)

    def test_it_sends_the_headers_the_messages_api_requires(self):
        source = routes_source()
        # x-api-key rather than a Bearer token, and the version header is
        # mandatory - omitting it is a 400 that reads like a bad request.
        self.assertIn('"x-api-key"', source)
        self.assertIn('"anthropic-version"', source)

    def test_the_system_prompt_is_a_top_level_parameter(self):
        # In the Messages API `system` is its own field, not a message with
        # role "system". Sending it as a message is a 400.
        source = routes_source()
        self.assertIn('"system": system_prompt', source)
        self.assertNotIn('{"role": "system"', source)


class TheModelIsNamedOnceAndMatchesTheClaim(unittest.TestCase):
    def brief_model(self):
        found = re.search(r'^BRIEF_MODEL = "([^"]+)"', routes_source(), re.M)
        self.assertIsNotNone(found, "BRIEF_MODEL is not defined")
        return found.group(1)

    def test_a_model_is_named(self):
        self.assertTrue(self.brief_model())

    def test_the_ui_footer_does_not_credit_a_different_model(self):
        # The footer says "Generated by Claude Haiku". It said that while the
        # code called Grok, which is how a UI ends up describing a provider
        # the application cannot reach.
        footer = BRIEF_UI.read_text(encoding="utf-8")
        claimed = re.search(r"Generated by ([A-Za-z0-9 .\-]+?)\s*[·<]", footer)
        self.assertIsNotNone(claimed, "the brief footer no longer names a model")
        claim = claimed.group(1).strip().lower()

        model = self.brief_model().lower()
        for word in claim.split():
            with self.subTest(word=word):
                self.assertIn(
                    word, model,
                    f"the footer credits {claim!r} but the handler calls {model!r}",
                )

    def test_the_response_is_parsed_as_content_blocks(self):
        # The Messages API returns content blocks, not choices[0].message.
        source = routes_source()
        self.assertIn('block.get("type") == "text"', source)
        self.assertNotIn('data["choices"][0]', source)


class TheErrorPathDoesNotLeak(unittest.TestCase):
    def test_the_client_is_not_told_the_exception_text(self):
        # F-0010: an httpx error can carry request detail. The handler logs a
        # type and returns a flat message.
        source = routes_source()
        self.assertIn('detail="analysis failed"', source)


if __name__ == "__main__":
    unittest.main()
