"""D-0069 / F-0084: the brief must call a provider this app can authenticate.

The handler required `GROK_API_KEY` and called `api.x.ai`. That key has never
been set on this application, so every brief returned:

    503 GROK_API_KEY not configured

`ANTHROPIC_API_KEY` had been deployed the whole time, and the panel's own
footer has always read "Generated by Claude Haiku". Three things disagreed:
what the UI claimed, what the code called, and what the environment could
authenticate. Nothing compared them.
"""
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROUTES = ROOT / "api" / "routes.py"
BRIEF_UI = ROOT / "ui" / "src" / "components" / "country" / "AnalystBrief.jsx"


def routes_source():
    return ROUTES.read_text(encoding="utf-8")


class BothProvidersAreWiredCorrectly(unittest.TestCase):
    """D-0069 made this Anthropic-only; D-0071 made it selectable with Grok
    as the default. These assertions moved with it rather than being relaxed:
    each provider must still be wired the way ITS api requires."""

    def test_both_endpoints_are_present(self):
        source = routes_source()
        self.assertIn("https://api.anthropic.com/v1/messages", source)
        self.assertIn("https://api.x.ai/v1/chat/completions", source)

    def test_it_guards_on_whichever_key_the_chosen_provider_needs(self):
        # No hardcoded key name: the guard reads the setting named by the
        # selected provider's spec.
        source = routes_source()
        self.assertIn('getattr(settings, spec["setting"], "")', source)
        self.assertNotIn("GROK_API_KEY not configured", source)
        self.assertNotIn("ANTHROPIC_API_KEY not configured", source)

    def test_anthropic_sends_the_headers_its_api_requires(self):
        # x-api-key rather than a Bearer token, and the version header is
        # mandatory - omitting it is a 400 that reads like a bad request.
        source = routes_source()
        self.assertIn('"x-api-key": key', source)
        self.assertIn('"anthropic-version"', source)

    def test_grok_sends_a_bearer_token(self):
        self.assertIn('"Authorization": f"Bearer {key}"', routes_source())

    def test_the_system_prompt_goes_where_each_api_wants_it(self):
        # Anthropic: a top-level `system` field. OpenAI-style: a message with
        # role "system". Sending either one the other way is a 400.
        source = routes_source()
        self.assertIn('"system": system,', source)
        self.assertIn('{"role": "system", "content": system}', source)


class TheModelIsNamedOnceAndMatchesTheClaim(unittest.TestCase):
    def brief_model(self):
        from api.routes import BRIEF_PROVIDERS, DEFAULT_BRIEF_PROVIDER
        return BRIEF_PROVIDERS[DEFAULT_BRIEF_PROVIDER]["model"]

    def test_a_model_is_named(self):
        self.assertTrue(self.brief_model())

    def test_the_ui_footer_is_no_longer_hardcoded(self):
        # D-0071: the footer credits whichever provider ANSWERED, reported by
        # the server. A hardcoded name is what made F-0084 possible.
        footer = BRIEF_UI.read_text(encoding="utf-8")
        self.assertIn("Generated by {modelLabel}", footer)
        self.assertNotIn("Generated by Claude Haiku", footer)

    def _retired_test_the_ui_footer_does_not_credit_a_different_model(self):
        # The footer says "Generated by Claude Haiku". It said that while the
        # code called Grok, which is how a UI ends up describing a provider
        # the application cannot reach.
        footer = BRIEF_UI.read_text(encoding="utf-8")
        claimed = re.search(r"Generated by ([A-Za-z0-9 .\-]+?)\s*[·<]", footer)
        self.assertIsNotNone(claimed, "the brief footer no longer names a model")
        claim = claimed.group(1).strip().lower()

        model = self.brief_model().lower()
        for word in claim.split():
            with self.subTest(word=word):
                self.assertIn(
                    word, model,
                    f"the footer credits {claim!r} but the handler calls {model!r}",
                )

    def test_each_response_shape_is_parsed_its_own_way(self):
        # Anthropic returns content blocks; the OpenAI-style api returns
        # choices[0].message.content. One parser for both would drop text.
        source = routes_source()
        self.assertIn('block.get("type") == "text"', source)
        self.assertIn('data.get("choices")', source)


class TheErrorPathDoesNotLeak(unittest.TestCase):
    def test_the_client_is_not_told_the_exception_text(self):
        # F-0010: an httpx error can carry request detail. The handler logs a
        # type and returns a flat message.
        source = routes_source()
        self.assertIn('detail="analysis failed"', source)


class TheProviderTableIsTheSingleSourceOfTruth(unittest.TestCase):
    """D-0071.

    F-0084 was three places disagreeing about which provider was in use. The
    way not to have that again is to have one place that knows, so the table
    holds everything that differs between providers - key, endpoint, model,
    and how to read the response - and the handler reads only from it.
    """

    def table(self):
        from api.routes import BRIEF_PROVIDERS
        return BRIEF_PROVIDERS

    def test_both_providers_are_declared(self):
        self.assertEqual(sorted(self.table()), ["anthropic", "grok"])

    def test_the_default_is_grok(self):
        from api.routes import DEFAULT_BRIEF_PROVIDER
        self.assertEqual(DEFAULT_BRIEF_PROVIDER, "grok")
        self.assertIn(DEFAULT_BRIEF_PROVIDER, self.table())

    def test_every_entry_is_complete(self):
        for pid, spec in self.table().items():
            with self.subTest(provider=pid):
                for field in ("label", "model", "setting", "env", "build", "parse"):
                    self.assertIn(field, spec, f"{pid} has no {field}")
                self.assertTrue(callable(spec["build"]))
                self.assertTrue(callable(spec["parse"]))

    def test_each_setting_exists_on_Settings(self):
        # A spec naming a setting that does not exist resolves to "" via
        # getattr's default and reports the provider as unavailable forever -
        # a silent misconfiguration rather than an error.
        from config import Settings
        for pid, spec in self.table().items():
            with self.subTest(provider=pid):
                self.assertIn(spec["setting"], Settings.model_fields)

    def test_the_handler_reads_only_from_the_table(self):
        source = routes_source()
        handler = source[source.index("async def analyze_country"):]
        handler = handler[: handler.index("@router.get")]
        # No provider-specific literal may appear in the handler body.
        for literal in ("api.x.ai", "api.anthropic.com", "grok-2-latest",
                        "claude-haiku", "x-api-key", "Bearer "):
            with self.subTest(literal=literal):
                self.assertNotIn(literal, handler)


class TheProvidersEndpointNeverLeaksAKey(unittest.TestCase):
    def test_it_reports_presence_only(self):
        from api.routes import brief_provider_availability
        for row in brief_provider_availability():
            with self.subTest(provider=row["id"]):
                self.assertIsInstance(row["available"], bool)
                self.assertEqual(
                    set(row), {"id", "label", "model", "available", "default"},
                    "the providers endpoint must expose nothing but presence",
                )

    def test_exactly_one_provider_is_marked_default(self):
        from api.routes import brief_provider_availability
        defaults = [r for r in brief_provider_availability() if r["default"]]
        self.assertEqual(len(defaults), 1)


class TheResponseSaysWhichProviderAnswered(unittest.TestCase):
    def test_the_handler_returns_the_provider_and_model(self):
        # The footer credits what ANSWERED. Those differ from what was asked
        # for the moment a default changes, which is how F-0084 started.
        source = routes_source()
        self.assertIn('"provider": provider_id', source)
        self.assertIn('"model": spec["model"]', source)


if __name__ == "__main__":
    unittest.main()
