/**
 * The Sentinel analyst brief panel.
 *
 * The brief arrives as plain text with three recognised section headings. Any
 * other line renders as body text, so a brief whose shape changes degrades to
 * an unformatted paragraph rather than to an empty panel.
 */
const HEADINGS = /^(SITUATION|WHAT TO WATCH|RISK FACTORS)/i;

function BriefBody({ narrative }) {
  return (
    <div style={{ borderTop: "1px solid #1A2530", paddingTop: 14 }}>
      {narrative.split("\n").map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} style={{ height: 6 }} />;
        if (HEADINGS.test(trimmed)) {
          return (
            <div key={i} style={{ fontFamily: "monospace", fontSize: 10, color: "#C8A96E", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 4, marginTop: i > 0 ? 14 : 0 }}>
              {trimmed}
            </div>
          );
        }
        return (
          <div key={i} style={{ fontFamily: "monospace", fontSize: 12, color: "#8A9BAC", lineHeight: 1.8, marginBottom: 2 }}>
            {trimmed}
          </div>
        );
      })}
      <div style={{ fontFamily: "monospace", fontSize: 10, color: "#1E2D3D", marginTop: 12, borderTop: "1px solid #1A2530", paddingTop: 8 }}>
        Generated by Claude Haiku · Data: US Treasury TIC · World Gold Council · FRED
      </div>
    </div>
  );
}

export function AnalystBrief({ narrative, loading, onGenerate }) {
  return (
    <div style={{ background: "#060D14", border: "1px solid #C8A96E33", borderLeft: "3px solid #C8A96E", borderRadius: 2, padding: "16px 20px", marginTop: 16 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: narrative || loading ? 16 : 0 }}>
        <div>
          <div style={{ fontFamily: "monospace", fontSize: 11, color: "#C8A96E", letterSpacing: "0.1em", marginBottom: 2 }}>SENTINEL ANALYST BRIEF</div>
          {!narrative && !loading && (
            <div style={{ fontFamily: "monospace", fontSize: 11, color: "#3A4D5C" }}>
              AI-generated analysis using treasury, gold, and yield spread data
            </div>
          )}
        </div>
        <button
          onClick={onGenerate}
          disabled={loading}
          style={{ background: loading ? "#0F1923" : "#C8A96E18", border: `1px solid ${loading ? "#1E2D3D" : "#C8A96E"}`, color: loading ? "#3A4D5C" : "#C8A96E", borderRadius: 2, padding: "8px 16px", cursor: loading ? "not-allowed" : "pointer", fontFamily: "monospace", fontSize: 12, whiteSpace: "nowrap" }}>
          {loading ? "⟳ Generating..." : narrative ? "↻ Regenerate" : "▶ Generate Analysis"}
        </button>
      </div>
      {loading && (
        <div style={{ fontFamily: "monospace", fontSize: 12, color: "#3A4D5C", lineHeight: 1.8 }}>
          Analyzing treasury holdings, gold reserves, and sovereign spread data...
        </div>
      )}
      {narrative && !loading && <BriefBody narrative={narrative} />}
    </div>
  );
}
