import { useState } from "react";

/**
 * The Sentinel analyst brief panel.
 *
 * The brief arrives as plain text with three recognised section headings. Any
 * other line renders as body text, so a brief whose shape changes degrades to
 * an unformatted paragraph rather than to an empty panel.
 */
const HEADINGS = /^(SITUATION|WHAT TO WATCH|RISK FACTORS)/i;

function BriefBody({ narrative, modelLabel }) {
  return (
    <div style={{ borderTop: "1px solid #1A2530", paddingTop: 14 }}>
      {narrative.split("\n").map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} style={{ height: 6 }} />;
        if (HEADINGS.test(trimmed)) {
          return (
            <div key={i} style={{ fontFamily: "monospace", fontSize: 10, color: "#C8A96E", letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 4, marginTop: i > 0 ? 14 : 0 }}>
              {trimmed}
            </div>
          );
        }
        return (
          <div key={i} style={{ fontFamily: "monospace", fontSize: 12, color: "#8A9BAC", lineHeight: 1.8, marginBottom: 2 }}>
            {trimmed}
          </div>
        );
      })}
      <div style={{ fontFamily: "monospace", fontSize: 10, color: "#1E2D3D", marginTop: 12, borderTop: "1px solid #1A2530", paddingTop: 8 }}>
        Generated by {modelLabel} · Data: US Treasury TIC · World Gold Council · FRED
      </div>
    </div>
  );
}

/**
 * D-0071. The provider is chosen here and reported back by the server.
 *
 * `providers` comes from `/api/analyze/providers`, which reports only whether
 * a key is PRESENT. Offering a provider whose key is absent would produce a
 * 503 the reader cannot act on, which is `F-0084` made interactive — so an
 * unavailable provider is shown, disabled, and says why.
 */
export function AnalystBrief({ narrative, loading, onGenerate, providers = [], provider, defaultProvider }) {
  const usable = providers.filter((p) => p.available);
  const initial = defaultProvider && usable.some((p) => p.id === defaultProvider)
    ? defaultProvider
    : usable[0]?.id;
  const [chosen, setChosen] = useState(initial);
  const active = chosen ?? initial;

  // The footer credits what ANSWERED, not what was asked for. Those differ
  // the moment a default changes or a request falls back.
  const answered = providers.find((p) => p.id === provider);
  const modelLabel = answered ? answered.label : (providers.find((p) => p.id === active)?.label ?? "an AI model");

  return (
    <div style={{ background: "#060D14", border: "1px solid #C8A96E33", borderLeft: "3px solid #C8A96E", borderRadius: 2, padding: "16px 20px", marginTop: 16 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: narrative || loading ? 16 : 0 }}>
        <div>
          <div style={{ fontFamily: "monospace", fontSize: 11, color: "#C8A96E", letterSpacing: "0.1em", marginBottom: 2 }}>SENTINEL ANALYST BRIEF</div>
          {!narrative && !loading && (
            <div style={{ fontFamily: "monospace", fontSize: 11, color: "#3A4D5C" }}>
              AI-generated analysis using treasury, gold, and yield spread data
            </div>
          )}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          {providers.length > 1 && (
            <div style={{ display: "flex", border: "1px solid #1E2D3D", borderRadius: 2, overflow: "hidden" }}>
              {providers.map((p) => (
                <button
                  key={p.id}
                  onClick={() => p.available && setChosen(p.id)}
                  disabled={!p.available || loading}
                  title={p.available ? `${p.label} — ${p.model}` : `${p.label} is not configured on this deployment`}
                  style={{
                    background: active === p.id ? "#C8A96E18" : "transparent",
                    border: "none",
                    borderLeft: "1px solid #1E2D3D",
                    color: !p.available ? "#2A3540" : active === p.id ? "#C8A96E" : "#5A6878",
                    padding: "5px 10px",
                    cursor: p.available && !loading ? "pointer" : "not-allowed",
                    fontFamily: "monospace",
                    fontSize: 11,
                  }}>
                  {p.label}{!p.available && " ·"}
                </button>
              ))}
            </div>
          )}
        <button
          // Not disabled when `active` is unset. The selector depends on
          // /analyze/providers; if that is slow or down, `active` is
          // undefined and onGenerate omits the provider, so the SERVER
          // applies its default. The feature degrades to the behaviour it
          // had before the selector existed rather than locking the button.
          onClick={() => onGenerate(active)}
          disabled={loading}
          style={{ background: loading ? "#0F1923" : "#C8A96E18", border: `1px solid ${loading ? "#1E2D3D" : "#C8A96E"}`, color: loading ? "#3A4D5C" : "#C8A96E", borderRadius: 2, padding: "8px 16px", cursor: loading ? "not-allowed" : "pointer", fontFamily: "monospace", fontSize: 12, whiteSpace: "nowrap" }}>
          {loading ? "⟳ Generating..." : narrative ? "↻ Regenerate" : "▶ Generate Analysis"}
        </button>
        </div>
      </div>
      {loading && (
        <div style={{ fontFamily: "monospace", fontSize: 12, color: "#3A4D5C", lineHeight: 1.8 }}>
          Analyzing treasury holdings, gold reserves, and sovereign spread data...
        </div>
      )}
      {narrative && !loading && <BriefBody narrative={narrative} modelLabel={modelLabel} />}
    </div>
  );
}
